# Comprehensive chart format schemas with examples
SUPPORTED_CHART_FORMATS = {
    # Bar Charts
    "bar-standard": {
        "required_keys": ["type", "title", "description", "dataKey", "nameKey", "data"],
        "example": {
            "type": "bar-standard",
            "title": "Monthly Revenue",
            "description": "Monthly revenue breakdown",
            "dataKey": "revenue",
            "nameKey": "month",
            "data": [
                {"month": "January", "revenue": 45000},
                {"month": "February", "revenue": 52000},
                {"month": "March", "revenue": 48000},
            ],
        },
    },
    # "bar-multiple": {
    #     "required_keys": ["type", "title", "description", "dataKey", "nameKey", "xAxisKey", "layout", "data"],
    #     "example": {
    #         "type": "bar-multiple",
    #         "title": "Monthly Desktop vs Mobile",
    #         "description": "Comparison of desktop and mobile usage",
    #         "dataKey": "usage",
    #         "nameKey": "month",
    #         "xAxisKey": "month",
    #         "layout": "vertical",
    #         "data": [
    #             {"month": "January", "desktop": 186, "mobile": 80},
    #             {"month": "February", "desktop": 305, "mobile": 200}
    #         ]
    #     }
    # },
    "bar-stacked": {
        "required_keys": [
            "type",
            "title",
            "description",
            "xAxisKey",
            "nameKey",
            "groupedKeys",
            "data",
        ],
        "example": {
            "type": "bar-stacked",
            "title": "Quarterly Revenue Breakdown",
            "description": "Revenue by product, service, and support",
            "xAxisKey": "quarter",
            "nameKey": "quarter",
            "groupedKeys": ["product", "service", "support"],
            "data": [
                {"quarter": "Q1", "product": 100, "service": 50, "support": 25},
                {"quarter": "Q2", "product": 120, "service": 60, "support": 30},
            ],
        },
    },
    "bar-negative": {
        "required_keys": [
            "type",
            "title",
            "description",
            "xAxisKey",
            "groupedKeys",
            "legend",
            "data",
        ],
        "example": {
            "type": "bar-negative",
            "title": "Profit/Loss by Month",
            "description": "Monthly profit and loss",
            "xAxisKey": "month",
            "groupedKeys": ["profit"],
            "legend": True,
            "data": [
                {"month": "January", "profit": -500},
                {"month": "February", "profit": 1200},
                {"month": "March", "profit": -300},
            ],
        },
    },
    # Area Charts
    "area-standard": {
        "required_keys": [
            "type",
            "title",
            "description",
            "dataKey",
            "nameKey",
            "color",
            "data",
        ],
        "example": {
            "type": "area-standard",
            "title": "Monthly Visitors",
            "description": "Website visitor trend",
            "dataKey": "visitors",
            "nameKey": "month",
            "color": "hsl(207, 90%, 54%)",
            "data": [
                {"month": "January", "visitors": 186},
                {"month": "February", "visitors": 305},
                {"month": "March", "visitors": 237},
            ],
        },
    },
    "area-linear": {
        "required_keys": [
            "type",
            "title",
            "description",
            "dataKey",
            "nameKey",
            "color",
            "data",
        ],
        "example": {
            "type": "area-linear",
            "title": "Performance Over Time",
            "description": "System performance metrics",
            "dataKey": "performance",
            "nameKey": "hour",
            "color": "hsl(120, 60%, 40%)",
            "data": [
                {"hour": "00:00", "performance": 95},
                {"hour": "06:00", "performance": 87},
                {"hour": "12:00", "performance": 92},
            ],
        },
    },
    "area-stacked": {
        "required_keys": [
            "type",
            "title",
            "description",
            "groupedKeys",
            "xAxisKey",
            "data",
        ],
        "example": {
            "type": "area-stacked",
            "title": "Traffic Sources",
            "description": "Device traffic distribution over time",
            "groupedKeys": ["desktop", "mobile", "tablet"],
            "xAxisKey": "month",
            "data": [
                {"month": "January", "desktop": 186, "mobile": 80, "tablet": 45},
                {"month": "February", "desktop": 305, "mobile": 200, "tablet": 67},
            ],
        },
    },
    # Line Charts
    "line-standard": {
        "required_keys": [
            "type",
            "title",
            "description",
            "dataKey",
            "nameKey",
            "color",
            "data",
        ],
        "example": {
            "type": "line-standard",
            "title": "Performance Trend",
            "description": "System performance over time",
            "dataKey": "performance",
            "nameKey": "hour",
            "color": "hsl(220, 75%, 55%)",
            "data": [
                {"hour": "00:00", "performance": 95},
                {"hour": "06:00", "performance": 87},
                {"hour": "12:00", "performance": 92},
            ],
        },
    },
    "line-linear": {
        "required_keys": [
            "type",
            "title",
            "description",
            "dataKey",
            "nameKey",
            "color",
            "legend",
            "data",
        ],
        "example": {
            "type": "line-linear",
            "title": "Status Over Time",
            "description": "System status monitoring",
            "dataKey": "status",
            "nameKey": "time",
            "color": "hsl(340, 70%, 50%)",
            "legend": False,
            "data": [
                {"time": "00:00", "status": 100},
                {"time": "04:00", "status": 100},
                {"time": "08:00", "status": 95},
            ],
        },
    },
    # "line-multiple": {
    #     "required_keys": [
    #         "type",
    #         "title",
    #         "description",
    #         "dataKey",
    #         "groupedKeys",
    #         "color",
    #         "legend",
    #         "data",
    #     ],
    #     "example": {
    #         "type": "line-multiple",
    #         "title": "Desktop vs Mobile Usage",
    #         "description": "Usage comparison over time",
    #         "dataKey": "usage",
    #         "groupedKeys": ["desktop", "mobile"],
    #         "color": ["hsl(220, 75%, 50%)", "hsl(30, 85%, 55%)"],
    #         "legend": True,
    #         "data": [
    #             {"month": "January", "desktop": 186, "mobile": 80},
    #             {"month": "February", "desktop": 305, "mobile": 200},
    #         ],
    #     },
    # },
    # "line-dots": {
    #     "required_keys": [
    #         "type",
    #         "title",
    #         "description",
    #         "dataKey",
    #         "color",
    #         "legend",
    #         "dots",
    #         "data",
    #     ],
    #     "example": {
    #         "type": "line-dots",
    #         "title": "Quarterly Performance",
    #         "description": "Performance with visible data points",
    #         "dataKey": "value",
    #         "color": "hsl(10, 80%, 50%)",
    #         "legend": False,
    #         "dots": True,
    #         "data": [
    #             {"quarter": "Q1", "value": 45},
    #             {"quarter": "Q2", "value": 52},
    #             {"quarter": "Q3", "value": 48},
    #         ],
    #     },
    # },
    "line-label": {
        "required_keys": [
            "type",
            "title",
            "description",
            "dataKey",
            "xAxisKey",
            "customLabel",
            "data",
        ],
        "example": {
            "type": "line-label",
            "title": "Sales Performance",
            "description": "Revenue with visible values",
            "dataKey": "sales",
            "xAxisKey": "rep",
            "customLabel": "${{value}}K",
            "data": [
                {"rep": "John", "sales": 45},
                {"rep": "Jane", "sales": 67},
                {"rep": "Bob", "sales": 52},
            ],
        },
    },
    # Pie Charts
    "pie-standard": {
        "required_keys": ["type", "title", "description", "dataKey", "nameKey", "data"],
        "example": {
            "type": "pie-standard",
            "title": "Browser Usage",
            "description": "Distribution of browser usage",
            "dataKey": "visitors",
            "nameKey": "source",
            "data": [
                {"source": "chrome", "visitors": 275},
                {"source": "safari", "visitors": 200},
                {"source": "firefox", "visitors": 187},
            ],
        },
    },
    "pie-label": {
        "required_keys": [
            "type",
            "title",
            "description",
            "dataKey",
            "nameKey",
            "label",
            "legend",
            "data",
        ],
        "example": {
            "type": "pie-label",
            "title": "Product Revenue",
            "description": "Revenue by product category",
            "dataKey": "revenue",
            "nameKey": "product",
            "label": True,
            "legend": False,
            "data": [
                {"product": "Desktop", "revenue": 186000},
                {"product": "Mobile", "revenue": 305000},
                {"product": "Tablet", "revenue": 237000},
            ],
        },
    },
    "pie-interactive": {
        "required_keys": [
            "type",
            "title",
            "description",
            "dataKey",
            "nameKey",
            "legend",
            "data",
        ],
        "example": {
            "type": "pie-interactive",
            "title": "Regional Sales",
            "description": "Sales distribution by region",
            "dataKey": "sales",
            "nameKey": "region",
            "legend": True,
            "data": [
                {"region": "North America", "sales": 45000},
                {"region": "Europe", "sales": 32000},
                {"region": "Asia Pacific", "sales": 28000},
            ],
        },
    },
    "pie-donut": {
        "required_keys": [
            "type",
            "title",
            "description",
            "dataKey",
            "nameKey",
            "legend",
            "data",
        ],
        "example": {
            "type": "pie-donut",
            "title": "Monthly Desktop Usage",
            "description": "Desktop usage by month",
            "dataKey": "desktop",
            "nameKey": "month",
            "legend": True,
            "data": [
                {"month": "january", "desktop": 186},
                {"month": "february", "desktop": 305},
                {"month": "march", "desktop": 237},
            ],
        },
    },
    # Radar Charts
    "radar-standard": {
        "required_keys": [
            "type",
            "title",
            "description",
            "dataKey",
            "nameKey",
            "color",
            "legend",
            "data",
        ],
        "example": {
            "type": "radar-standard",
            "title": "Skill Assessment",
            "description": "Employee skill evaluation",
            "dataKey": "score",
            "nameKey": "skill",
            "color": "hsl(140, 70%, 45%)",
            "legend": False,
            "data": [
                {"skill": "Communication", "score": 95},
                {"skill": "Technical", "score": 87},
                {"skill": "Leadership", "score": 78},
            ],
        },
    },
    "radar-lines-only": {
        "required_keys": [
            "type",
            "title",
            "description",
            "dataKey",
            "nameKey",
            "color",
            "legend",
            "data",
        ],
        "example": {
            "type": "radar-lines-only",
            "title": "Performance Metrics",
            "description": "System performance evaluation",
            "dataKey": "value",
            "nameKey": "metric",
            "color": "hsl(250, 65%, 50%)",
            "legend": False,
            "data": [
                {"metric": "Speed", "value": 88},
                {"metric": "Quality", "value": 92},
                {"metric": "Efficiency", "value": 85},
            ],
        },
    },
    # "radar-multiple": {
    #     "required_keys": [
    #         "type",
    #         "title",
    #         "description",
    #         "dataKey",
    #         "color",
    #         "legend",
    #         "grid",
    #         "data",
    #     ],
    #     "example": {
    #         "type": "radar-multiple",
    #         "title": "Team Comparison",
    #         "description": "Performance comparison between teams",
    #         "dataKey": "score",
    #         "color": "hsl(200, 70%, 50%)",
    #         "legend": False,
    #         "grid": False,
    #         "data": [
    #             {"category": "Sales", "teamA": 95, "teamB": 87},
    #             {"category": "Marketing", "teamA": 78, "teamB": 92},
    #         ],
    #     },
    # },
    # Radial Charts
    "radial-standard": {
        "required_keys": [
            "type",
            "title",
            "description",
            "dataKey",
            "groupedKeys",
            "color",
            "legend",
            "data",
        ],
        "example": {
            "type": "radial-standard",
            "title": "Monthly Visitors",
            "description": "Visitor statistics over time",
            "dataKey": "visitors",
            "groupedKeys": ["visitors"],
            "color": ["hsl(210, 70%, 50%)"],
            "legend": True,
            "data": [
                {"month": "January", "visitors": 186},
                {"month": "February", "visitors": 305},
                {"month": "March", "visitors": 237},
            ],
        },
    },
    "radial-stacked": {
        "required_keys": [
            "type",
            "title",
            "description",
            "groupedKeys",
            "nameKey",
            "data",
        ],
        "example": {
            "type": "radial-stacked",
            "title": "Revenue Breakdown",
            "description": "Quarterly revenue by department",
            "groupedKeys": ["sales", "marketing", "support"],
            "nameKey": "quarter",
            "data": [
                {"quarter": "Q1", "sales": 45000, "marketing": 12000, "support": 8000},
                {"quarter": "Q2", "sales": 52000, "marketing": 15000, "support": 10000},
            ],
        },
    },
    "radial-progress": {
        "required_keys": [
            "type",
            "title",
            "description",
            "dataKey",
            "nameKey",
            "centerText",
            "centerLabel",
            "data",
        ],
        "example": {
            "type": "radial-progress",
            "title": "Goal Progress",
            "description": "Project completion status",
            "dataKey": "progress",
            "nameKey": "category",
            "centerText": "87%",
            "centerLabel": "Complete",
            "data": [{"category": "Progress", "progress": 87}],
        },
    },
}
